spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/bank_db
      username: admin
      password: qwe123
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank_db
    username: admin
    password: qwe123
    driver-class-name: org.postgresql.Driver

integration:
  rateFinder:
    nbp:
      name: nbp-exchange-rate-client
      url: https://api.nbp.pl/
      path: /api/exchangerates
      defaultTable: A